name: MkDocs Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - "mkdocs.yml"
      - "docs/**"
  pull_request:
    branches: [ main, master ]
    paths:
      - "mkdocs.yml"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy MkDocs
        uses: Reloaded-Project/devops-mkdocs@v1
        with:
          requirements: ./docs/requirements.txt
          publish-to-pages: ${{ github.event_name == 'push' }}
          checkout-current-repo: true